updates and refactoring to openvpn-auth-oauth2 (https://github.com/jkroepke/openvpn-auth-oauth2) fix container build error:
ERROR: unable to select packages:
  openvpn-auth-azure-ad (no such package):
    required by: world[openvpn-auth-azure-ad]